### ISSUE TITLE
Manjaro awesome new maintainer needed

### ISSUE THREAD

**Issue by bittin** [manjaro/community-editions#15]
Hey!

Archived my Manjaro awesome isos: https://github.com/bittin/iso-build/
as i don't really take care of them and Manjaro removed the support
from them in May, but can unarchive and give the repo to someone else
if someone else want to take the burden of me and take care of them
instead of me

**Comment by yochananmarqos** [comment]
Thank you for letting us know. Creating multiple issues, emailing three mailing list and posting on the forum is quite enough.
